---
spring:
  jpa:
    show_sql: false
    generate-ddl: false
  flyway:
    default-schema: university
  thymeleaf:
    enabled: true
    cache: false
---
spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://64701c1104e2:f193b9be1391@postgres-84fee189-7163-459b-b15e-fad663f19e8f.cqryblsdrbcs.us-east-1.rds.amazonaws.com:4967/qPvPQAAnYWNi
    username: 64701c1104e2
    password: f193b9be1391
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university
    username: university
    password: 1234
  jpa:
    show_sql: false
 
    
logging:
  level:
    root: warn
    org.springframework.web: debug
#    org.springframework.security: debug
#    org.hibernate: error
#    org.hibernate.sql: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.flywaydb: debug 
---
spring:
  config:
    activate:
      on-profile:
      - test
  flyway:
    enabled: false
  datasource:
    name: test
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  sql:
    init:
      mode: embedded
      platform: h2
  jpa:
    show-sql: true
    database-platform: H2
    generate-ddl: true
logging:
  level:
    root: warn
    org: warn
---
spring:
  config:
    activate:
      on-profile:
      - testcontainers
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14.0:///university?TC_INITSCRIPT=init-testcontainer-postgre.sql&TC_DAEMON=true
  jpa:
    show_sql: true        

    
    
        