---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/university
    username: university
    password: 1234
  jpa:
    hibernate.ddl-auto: none
    show_sql: false