---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://64701c1104e2:f193b9be1391@postgres-84fee189-7163-459b-b15e-fad663f19e8f.cqryblsdrbcs.us-east-1.rds.amazonaws.com:4967/qPvPQAAnYWNi
    username: 64701c1104e2
    password: f193b9be1391
  jpa:
    hibernate.ddl-auto: none
    show_sql: false